# Generated by Django 3.0.9 on 2020-11-17 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='memlimit',
            field=models.IntegerField(default=128),
        ),
        migrations.AddField(
            model_name='question',
            name='timelimit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='lang',
            field=models.CharField(choices=[('cpp', 'C++'), ('py', 'Python'), ('c', 'C')], max_length=10),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(default='None', max_length=32),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userdata', to=settings.AUTH_USER_MODEL),
        ),
    ]
