# Generated by Django 3.1 on 2020-11-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='memlimit',
        ),
        migrations.RemoveField(
            model_name='question',
            name='timelimit',
        ),
    ]
