# Generated by Django 3.0.9 on 2020-09-24 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='contest',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.Contest'),
            preserve_default=False,
        ),
    ]
