# Generated by Django 3.1 on 2020-11-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201118_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='memlimit',
            field=models.IntegerField(default=128),
        ),
        migrations.AddField(
            model_name='question',
            name='timelimit',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
        ),
    ]
