# Generated by Django 3.0.9 on 2020-11-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201117_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='timelimit',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
        ),
    ]
