# Generated by Django 3.0.9 on 2020-11-17 21:55

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201118_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='tags',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
